
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"

export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"

export const USER_LOGGED_IN = "USER_LOGGED_IN"

export const GET_ALL_POST_LOADING = "GET_ALL_POST_LOADING"
export const GET_ALL_POST_SUCCESS ="GET_ALL_POST_SUCCESS"
export const GET_ALL_POST_FAILED = "GET_ALL_POST_FAILED"
